### ISSUE TITLE
sopare_service file does not work

### ISSUE THREAD

**Issue by ghost** [bishoph/Misc#2] opened 2020-12-30 13:40 UTC
I am trying to run sopare at boot on my raspberry pi. I have a plugin that saves recognised words to a database:

```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sqlite3
import time

def update_word_db(word):
    # connect to the database
    connection = sqlite3.connect("/home/pi/CODE_main/DATABASE_word.db")
    cursor = connection.cursor()
    
    current_time = time.time()
    
    # run an sql query and fetch results
    #cursor.execute("SELECT * FROM listen;")
    #listen = int(cursor.fetchall()[0][0])
    
    
    #if listen == 1: # only listen if required
    cursor.execute("INSERT INTO word (word, time) VALUES ('" + str(word) + "', '" + str(current_time) + "');")
    connection.commit()

    # close connection
    cursor.close()
    connection.close()

def run(readable_results, data, rawbuf):
    #print(readable_results)
    if len(readable_results) > 0:
        if len(readable_results) > 1 and readable_results[0] == "":
            update_word_db(readable_results[1])
        else:
            update_word_db(readable_results[0])
```

Using sopare_service as instructed, I modified sopare_service with my .conf file name and the sopare directory, copied sopare_service to /etc/init.d/ and ran `sudo update-rc.d sopare_service defaults`. After rebooting, no words were added to the database when I spoke them. Please advise on why this is the case, or if there's an alternative way for it to run on boot.

If it's important, in my installation on raspbian python3 is the default, so I have modified sopare.py, changing the first line to `#!/usr/bin/env python2`

**Comment by bishoph** [comment] 2020-12-30 14:28
No clue what the error is, but my guess is that running SOPARE from command line runs as user "pi" and from init.d runs as user "root" and that the reason why it fails. Make sure to log errors and post them with an issue because without errors and logs it's like looking in the dark and guessing wildly ;)

To test my theory just start python as user root from the command line and see what happens. Beside that, there is an option in my script to log errors into a file to see what's going on...

**Comment by ghost** [comment] 2020-12-30 14:34
running sudo ./sopare.py still runs sopare normally..
How do I enable error logging in sopare_service?

**Comment by bishoph** [comment] 2020-12-30 14:55
With the "-e" option in the DAEMON_ARGS:

<code>
DAEMON_ARGS="-i config/YOUR_CONFIG.ini -e -l"
</code>

SOPARE help output:
<pre>
-e --error          : redirect sdterr to error.log
</pre>

**Comment by ghost** [comment] 2020-12-30 15:03
okay, sorry, where is error.log located?

**Comment by bishoph** [comment] 2020-12-30 16:18
In the sopare directory where the readme and the sopare.py file is located

**Comment by ghost** [comment] 2020-12-30 19:24
The error.log file isn't there, do I need to create it first?

**Comment by bishoph** [comment] 2020-12-30 20:55
Normally the file will be created automatically...AFAIR. But you can also start SOPARE with the -e option from the command line to check if it works.

**Comment by ghost** [comment] 2020-12-31 09:48
I started sopare with the arguments listed in the sopare_service file, and a error.log file was generated. But attempting to run sopare from boot with the instructions from sopare_service, nothing is added to error.log, it is a blank file.

Looking through sopare_service this line caught my eye:

`
PIDFILE=/var/run/sopare_service.pid
`

I can't find sopare_service.pid in /var/run, could this be the problem?

Also what is the significance of this line:
`
#Required-Start:    $remote_fs $syslog
`

Does this need to be run after:
`
sudo update-rc.d sopare_service defaults
`

to start sopare from boot?

**Comment by bishoph** [comment] 2020-12-31 13:16
Did you test if python starts at all? If there is no pid file the possibility that nothing gets started is near 100%...I would do the following:

First, start the service from the command line:

<code>
sudo service sopare_service start
</code>

Please be aware that this command only works if you followed the steps to add the script as described here, specially the update-rc.d command is necessary:
https://raspberrytips.com/autostart-a-program-on-boot/

After you started the service you could see output/error. If all is green and starts normally test if SOPARE/python is running:

<code>
ps aux | grep sopare
</code>

You should see a list of python processes and the sopare command line arguments. If you see that, check if the "-e" option is included. 

Hope that helps.

**Comment by ghost** [comment] 2020-12-31 13:57
okay, I didn't know 
`
sudo chmod +x /etc/init.d/sopare_service
`
had to be run to start the script. Now sopare_service.pid apears in /var/run/ and running 
`
ps aux | grep sopare
`
produces the following output:
`
root       480  1.0  3.5 258620 66412 ?        S    13:51   0:02 python2 /home/pi/CODE_sopare/sopare.py -i config/default.ini -e -l
`
`
root       708  0.0  2.1 258620 40244 ?        S    13:51   0:00 python2 /home/pi/CODE_sopare/sopare.py -i config/default.ini -e -l
`
`
root       709  0.0  2.1 258620 40244 ?        S    13:51   0:00 python2 /home/pi/CODE_sopare/sopare.py -i config/default.ini -e -l
`
`
pi        1113  0.0  0.0   7348   572 pts/0    S+   13:55   0:00 grep --color=auto sopare
`
`

But nothing is appearing in the database and error.log is still blank.

**Comment by ghost** [comment] 2020-12-31 13:59
Perhaps the plugin simply isn't working, ill try saving the words to a different file instead

**Comment by ghost** [comment] 2020-12-31 14:11
I tried using a regular text file instead to no avail:
`
def run(readable_results, data, rawbuf):
`
`
    f = open("/home/pi/text.txt", "a")
`
`
    f.write(readable_results[0])
`
`
    f.close()
`

sopare seems to be running at least according to
`
ps aux | grep sopare
`
but the plugin is not. Any advice would be appriciated

**Comment by ghost** [comment] 2020-12-31 14:12
interestingly sopare_service.pid in /var/run only contains the number 482. Why would this be?

**Comment by ghost** [comment] 2020-12-31 14:27
Could perhaps it be a problem with the init info at the start of sopare_service? the file uses:

`
! /bin/sh
`
`
 BEGIN INIT INFO
`
`
 Provides:          sopare service
`
`
 Required-Start:    $remote_fs $syslog
`
`
 Required-Stop:     $remote_fs $syslog
`
`
 Default-Start:     2 3 4 5
`
`
 Default-Stop:      0 1 6
`
`
 Short-Description: sopare service
`
`
 Description:       SOPARE start/stop script for endless recording and error redirecting to error.log
`
`
 END INIT INFO
`

but https://raspberrytips.com/autostart-a-program-on-boot/
recommends this:

`
!/bin/bash
`
`
 BEGIN INIT INFO
`
`
 Provides: MyService
`
`
 Required-Start:    $all
`
`
 Required-Stop: 
`
`
 Default-Start:     5 
`
`
 Default-Stop:      6 
`
`
 Short-Description: Your service description
`
`
 END INIT INFO
`

sorry I had to remove the hashtags they were making everything bold. Sorry for sending you lot's of messages as well.

**Comment by bishoph** [comment] 2020-12-31 14:47
If SOPARE is running and there is no issue I will close this bug as works/invalid. 

The pid file is created by the OS and must be the only number in the file. Don't touch it as this is a system file. 

In terms of your plugin issue I can't help as I have no clue about your setup, your system etc. 
Please understand that the issues here are not meant to provide free developing support ;)

**Comment by ghost** [comment] 2020-12-31 14:57
The plugin is not the issue, as it runs fine when I run sopare manually.

**Comment by bishoph** [comment] 2020-12-31 15:13
You stated "Perhaps the plugin simply isn't working.,." and SOPARE just starts and runs fine - not sure where we stand then.

Please make sure to add as many information as possible, like log files, error messages and a clear how to reproduce description.

**Comment by ghost** [comment] 2020-12-31 15:25
Never mind I think the issue is that sopare is no longer detecting my microphone after an update and upgrade to raspbian

**Comment by ghost** [comment] 2020-12-31 15:30
that brings this up how do i select which audio card to use for sopare?

**Comment by bishoph** [comment] 2020-12-31 15:36
If you are using the latest testing branch you can setup your card in the config. This option was added by "herdtie" some weeks ago...

**Comment by ghost** [comment] 2020-12-31 15:37
nice, is that just the latest github download?

**Comment by bishoph** [comment] 2020-12-31 16:38
No, you need to checkout the branch. As it is the testing branch you should expect that not everything is working as expected or error free. You can also stick with the master branch which is more stable and configure the default card within the alsa config....

**Comment by ghost** [comment] 2020-12-31 16:47
okay, how do I change the default audio input to 2 using alsa? I can't find any up to date tutorials online

**Comment by bishoph** [comment] 2020-12-31 16:56
https://www.alsa-project.org/main/index.php/Setting_the_default_device

**Comment by ghost** [comment] 2020-12-31 17:02
/etc/asound.conf already exists for me, and adding those two lines did nothing

**Comment by bishoph** [comment] 2020-12-31 17:21
Sure it exists. There are maybe 3 config files for alsa depending on the OS/distro you are using and it also depends on the user who runs the process. Look, I asked for error messages and information to fix SOPARE related issues and you are complaining that changing a config file from a different project does not work. To put this into perspective: it's like using a recipe and ask the author that your custom build oven is not working...please understand that I'm really willing to help and to fix issues around SOPARE, but the level of support you are requesting here is quite a lot. Hope you understand this.

**Closed as completed** 2020-12-31 17:22 UTC
Labels: question, info needed, works as expected
